### PR TITLE
Correct idiomatic deictic expressions

### LINKED ISSUE #152: TTTTimeIntervalFormatter idiomatic date two days ago sometimes referred to as "yesterday"
Reproduction steps:

```
TTTTimeIntervalFormatter *formatter = [[TTTTimeIntervalFormatter alloc] init];
formatter.usesIdiomaticDeicticExpressions = YES;
NSDate *date = // 2015-02-22 15:33:50 +0000
NSDate *now = // 2015-02-24 10:13:39 +0000
NSString *human = [formatter stringForTimeIntervalFromDate:now toDate:date];
NSLog(@"Now: %@, Date: %@, Human: %@", now, date, human);
```

Output:

```
Now: 2015-02-24 10:13:39 +0000, Date: 2015-02-22 15:33:50 +0000, Human: yesterday
```

Expected output:

```
Human: 2 days ago
```

This line in TTTTimeIntervalFormatter looks only at the "day" component:

```
} else if ([components day] == -1 && [components year] == 0 && [components month] == 0 && [components weekOfYear] == 0) {
        return @"yesterday";
}
```

This results in all dates that are more than 24 hours ago, but less than 48 hours ago, being referred to as "yesterday", even when midnight has passed twice.

### PR DESCRIPTION
**Pull request by sebastianludwig**
Fixes #152. This should be merged after #185 because it relies on the conversion of `it.lproj/FormatterKit.strings` to UTF-8.

I also have a huge bunch of unit tests that I'll happily provide once #187 is merged.

### CODE REVIEW

**Comment by yas375** [comment]
:+1: I'd love to get this in! 

My plan is: 
1. make possible to add locale-specific unit tests (I'm working on it)
2. cover locale specific differences with unit tests
3. merge with confidence 😎

**Comment by sebastianludwig** [comment]
This is aages old. I should still have the unit tests lying around and I'm willing to contribute them. However, I won't adopt them to any new style, since I've got my own more targeted pod for this kind of task now.

**Comment by damienrambout** [comment]
+1 👍

**Comment by mattt** [comment]
Thanks so much for this, @sebastianludwig. This is now merged as of e890a18c4af9351413d138329764ac3bc4b4a314. Apologies for taking so long to get this in.

**Pull request closed without merging**
